apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.clusterName }}-setup-passwords
  labels:
    app: {{ .Values.clusterName }}
    component: setup-passwords
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 20
  template:
    metadata:
      labels:
        app: {{ .Values.clusterName }}
        component: setup-passwords
    spec:
      restartPolicy: OnFailure
      containers:
      - name: setup-passwords
        image: curlimages/curl:latest
        command:
          - sh
          - -c
          - |
            set -e

            echo "Waiting for Elasticsearch to be ready..."
            # Wait for port to be open (anonymous access allows this)
            until wget --spider -q "http://{{ .Values.clusterName }}-{{ .Values.nodeGroup }}:9200/_cluster/health" 2>/dev/null; do
              echo "Waiting for Elasticsearch..."
              sleep 5
            done

            echo "Elasticsearch is ready. Setting up user passwords..."

            # Set elastic user password using anonymous access (which has superuser role)
            curl -X POST "http://{{ .Values.clusterName }}-{{ .Values.nodeGroup }}:9200/_security/user/elastic/_password" \
              -H "Content-Type: application/json" \
              -d '{"password":"elastic"}' || {
                echo "Failed to set elastic password, but continuing..."
              }

            # Set kibana_system user password
            curl -X POST "http://{{ .Values.clusterName }}-{{ .Values.nodeGroup }}:9200/_security/user/kibana_system/_password" \
              -H "Content-Type: application/json" \
              -d '{"password":"kibana"}' || {
                echo "Failed to set kibana_system password, but continuing..."
              }

            echo "Password setup complete!"
